linters-settings:
  gocritic:
    # Which checks should be enabled; can't be combined with 'disabled-checks';
    # See https://go-critic.github.io/overview#checks-overview
    # To check which checks are enabled run `GL_DEBUG=gocritic golangci-lint run`
    # By default list of stable checks is used.
    disabled-checks:
      - commentedOutCode
      - commentFormatting

    # Enable multiple checks by tags, run `GL_DEBUG=gocritic golangci-lint run` to see all tags and checks.
    # Empty list by default. See https://github.com/go-critic/go-critic#usage -> section "Tags".
    enabled-tags:
      - performance
      - diagnostic
      - opinionated

    settings: # settings passed to gocritic
      rangeExprCopy:
        sizeThreshold: 16
      rangeValCopy:
        sizeThreshold: 16
linters:
  enable:
    - gocritic
